import type React from "react"
import type { Metadata } from "next"
import "@fontsource-variable/petrona"

export const metadata: Metadata = {
  title: "Collect all the Plants!",
  description: "Generated by create next app",
  generator: "v0.dev",
  icons: {
    icon: [{ url: "/api/favicon", type: "image/png" }],
    apple: [{ url: "/api/favicon", type: "image/png" }],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="de">
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
              * {
                font-family: 'Petrona Variable', system-ui, sans-serif !important;
              }
            `,
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  )
}

import "./globals.css"
